import { defineStore } from 'pinia'
import { ref } from 'vue'
import { nanoid } from 'nanoid'
import { supabase, GPX_BUCKET, getGpxPublicUrl } from '@/lib/supabase'
import type { Route, Difficulty } from '@/types'

export const useRoutesStore = defineStore('routes', () => {
  const routes = ref<Route[]>([])
  const loading = ref(false)
  const error = ref<string | null>(null)

  async function fetchRoutes() {
    loading.value = true
    error.value = null
    const { data, error: err } = await supabase
      .from('routes')
      .select('*')
      .eq('is_public', true)
      .order('created_at', { ascending: false })

    if (err) { error.value = err.message }
    else { routes.value = data as Route[] }
    loading.value = false
  }

  async function fetchRouteById(id: string): Promise<Route | null> {
    const { data, error: err } = await supabase
      .from('routes')
      .select('*')
      .eq('id', id)
      .single()
    if (err) return null
    return data as Route
  }

  async function fetchRouteByToken(token: string): Promise<Route | null> {
    const { data, error: err } = await supabase
      .from('routes')
      .select('*')
      .eq('share_token', token)
      .single()
    if (err) return null
    return data as Route
  }

  async function uploadRoute(
    file: File,
    meta: {
      name: string
      description: string
      difficulty: Difficulty | null
      distanceKm: number
      elevationGain: number
      userId: string
    },
  ): Promise<Route> {
    // Use nanoid only for the share token and a temporary file path slug.
    // The row UUID is generated by Supabase (gen_random_uuid()), so we
    // insert first to get the real UUID, then upload to storage with it.
    const shareToken = nanoid(10)

    const { data, error: insertErr } = await supabase
      .from('routes')
      .insert({
        user_id: meta.userId,
        name: meta.name,
        description: meta.description || null,
        distance_km: meta.distanceKm,
        elevation_gain: meta.elevationGain,
        difficulty: meta.difficulty,
        gpx_path: 'pending',   // placeholder — updated after upload
        share_token: shareToken,
        is_public: true,
      })
      .select()
      .single()

    if (insertErr) throw new Error(`Database insert failed: ${insertErr.message}`)

    const route = data as Route
    const gpxPath = `${meta.userId}/${route.id}.gpx`

    const { error: uploadErr } = await supabase.storage
      .from(GPX_BUCKET)
      .upload(gpxPath, file, { contentType: 'application/gpx+xml', upsert: false })

    if (uploadErr) {
      // Clean up orphaned row
      await supabase.from('routes').delete().eq('id', route.id)
      throw new Error(`Storage upload failed: ${uploadErr.message}`)
    }

    // Update the row with the real storage path
    const { data: updated, error: updateErr } = await supabase
      .from('routes')
      .update({ gpx_path: gpxPath })
      .eq('id', route.id)
      .select()
      .single()

    if (updateErr) throw new Error(`Failed to update GPX path: ${updateErr.message}`)

    return updated as Route
  }

  async function deleteRoute(route: Route) {
    await supabase.storage.from(GPX_BUCKET).remove([route.gpx_path])
    await supabase.from('routes').delete().eq('id', route.id)
    routes.value = routes.value.filter((r) => r.id !== route.id)
  }

  function getDownloadUrl(route: Route): string {
    return getGpxPublicUrl(route.gpx_path)
  }

  function getShareUrl(route: Route): string {
    return `${window.location.origin}/share/${route.share_token}`
  }

  return {
    routes,
    loading,
    error,
    fetchRoutes,
    fetchRouteById,
    fetchRouteByToken,
    uploadRoute,
    deleteRoute,
    getDownloadUrl,
    getShareUrl,
  }
})
